name: Java Maven CI dated on 29/1/2025

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Set up JDK 17 

        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'  

      - name: Build with Maven
        run: mvn -f pom.xml clean package

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GIT_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and tag Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/my-app:latest .
          docker tag ghcr.io/${{ github.repository }}/my-app:latest ghcr.io/${{ github.repository }}/my-app:v1.0

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository }}/my-app:latest
          docker push ghcr.io/${{ github.repository }}/my-app:v1.0
